project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Profile"
        contents: 
          - index.qmd
      - section: "Publications"
        contents:
          - journal.qmd
          - page2.qmd
      - section: "Lectures"
        contents:
          - page3.qmd
          - page4.qmd
          - page5.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true