project:
  type: book
  output-dir: docs

book:
  title: "Data Science and Economics"
  image: "figure/logo.png"
  author: "Moinul Islam"
  date: "5/1/2023"
  chapters:
    - index.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - chapter_6.qmd
    - chapter_7.qmd
    - references.qmd
bibliography: data_science.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

