project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Section 1"
        contents: 
          - chapter_1.qmd
      - section: "Section 2"
        contents:
          - chapter_2.qmd
          - chapter_3.qmd
      - section: "Section 3"
        contents:
          - chapter_4.qmd
          - chapter_5.qmd
          - chapter_6.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
   