project:
  type: book
  output-dir: docs

book:
  title: "Economic Data Science"
  author: "Moinul Islam"
  date: today
  chapters:
    - index.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - chapter_6.qmd
    - chapter_7.qmd
    - chapter_8.qmd
    - references.qmd
bibliography: data_science.bib

format:
  html:
    theme: 
       dark: darkly
       light: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

